on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  pre_build:
    name: Prepare index pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'dev'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './_tools/package-lock.json'
    - name: Change working directory to _tools
      run: cd _tools
    - name: Install dependencies
      run: npm install
      working-directory: './_tools'
    - name: Run Gallery
      run: ./run-gallery.sh
      working-directory: './_tools'
    - name: git setup
      run: |
        git config user.email "mailrino@gmail.com"
        git config user.name "Github Actions"
    - name: git commit and push
      run: ./commit.sh
      working-directory: './_tools'
